title: Java Programming Tips & Tricks.
email: your-email@domain.com
description: >
  Java Programming Tips & Tricks.
  Snippets of code to learn, understand and examplore.
baseurl: ""
url: "http://rememberjava.com"
github_username:  hblok

# Build settings
paginate: 5
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
